version: '3'
services:
  python:
    container_name: py
    image: python:3.9.13
    volumes:
      - './project:/home'
        #depends_on:
        #- mysql
    links:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - python-network
    environment:
      - PATH=$VIRTUAL_ENV/bin:$PATH
    working_dir: /home
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - python-network
networks:
  python-network:
    external: true
volumes:
  mysql-data: null
