version: '3'
services:
  python:
    container_name: py
    build:
      context: ./images/python
    volumes:
      - './project:/home'
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - python-network
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - python-network
networks:
  python-network:
    external: true
volumes:
  mysql-data: null
