# Generated by Django 4.0.5 on 2022-06-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_choise_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('choise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.choise')),
            ],
        ),
    ]
