# Generated by Django 4.0.5 on 2022-06-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_choiseuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='choiseuser',
            old_name='choise_id',
            new_name='choise',
        ),
        migrations.RemoveField(
            model_name='choiseuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='choiseuser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.user'),
            preserve_default=False,
        ),
    ]
